name: lint

on:
  pull_request:
    branches: [main]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install dependencies
        run: 'npm install'
      - name: Lint
        run: npm run lint:check